---
title: "Cleaning"
format: html
---

## Goals for this notebook
1. Evaluate data cleanliness
2. Select columns
3. Export clean data

## Setup

Loading the libraries.

```{r}
#| label: setup
#| message: false
#| warning: false

library(tidyverse)
library(janitor)
library(stringr)
```

## Importing

```{r}
unhoused_geocoded <- read_rds("data-processed/unhoused-geocoded.rds")
```

## 1.Evaluating data cleanliness

```{r}
unhoused_geocoded |> glimpse()
```

### 1.1 Fixing dates

```{r}
unhoused_dates <- unhoused_geocoded |> 
  mutate(offense_date = as_date(offense_date),
         judgment_date = as_date(judgment_date)
         )

unhoused_dates |> glimpse()
```

## 2. Grouping by dates

```{r}
unhoused_dates <- unhoused_dates |> 
  mutate(
    off_yr = year(offense_date), # offense year
    off_mo = month(offense_date), # offense month in numbers
    off_mo_label = month(offense_date, label = TRUE), # offense month written
    off_yday = yday(offense_date), # offense day/365
    jud_yr = year(judgment_date),
    jud_mo = month(judgment_date),
    jud_mo_label = month(judgment_date, label = TRUE),
    jud_yday = yday(judgment_date)
  ) |> 
  
glimpse()
```

## 3. Selecting columns

```{r}
unhoused_clean <- unhoused_dates |> 
  select(citation_number, 
         case_number,
         defendant_name,
         violation_code,
         violation_description,
         total_fine_amount_due,
         total_fine_amount_paid,
         total_fine_amount_dismissed,
         offense_date,
         judgment_date,
         judgement_disposition,
         full_address,
         latitude,
         longitude,
         off_yr,
         off_mo,
         off_mo_label,
         off_yday,
         jud_yr,
         jud_mo,
         jud_mo_label,
         jud_yday
         )

unhoused_clean |> glimpse()
```

## Exporting

```{r}
unhoused_clean |> 
  write_rds("data-processed/unhoused-clean.rds")
```




